security:
  oauth2:
    client:
      clientId: ##
      clientSecret: ##
      accessTokenUri: https://accounts.google.com/o/oauth2/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      clientAuthenticationScheme: form
      scope:
        - https://www.googleapis.com/auth/gmail.readonly
        - https://www.googleapis.com/auth/userinfo.profile
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
